const MODULE_CATALOG = Object.freeze([
  {
    id: 'ventas',
    label: 'Ventas',
    categoria: 'Ventas y Clientes',
    descripcion: 'Punto de venta, facturación y cierre diario.',
    obligatorio: true,
    preseleccionado: true,
    minPlan: 'basico',
  },
  {
    id: 'historial_ventas',
    label: 'Historial de Ventas',
    categoria: 'Ventas y Clientes',
    descripcion: 'Auditoría completa de transacciones y documentos.',
    obligatorio: true,
    preseleccionado: true,
    minPlan: 'basico',
  },
  {
    id: 'clientes',
    label: 'Clientes',
    categoria: 'Ventas y Clientes',
    descripcion: 'Gestión integral de la base de clientes.',
    obligatorio: true,
    preseleccionado: true,
    minPlan: 'basico',
  },
  {
    id: 'contactos',
    label: 'Contactos',
    categoria: 'Ventas y Clientes',
    descripcion: 'Directorio extendido para proveedores y aliados.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'basico',
  },
  {
    id: 'taller',
    label: 'Taller',
    categoria: 'Operaciones Taller',
    descripcion: 'Activa la suite completa de funcionalidades para taller.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'pro',
  },
  {
    id: 'ordenes_trabajo',
    label: 'Órdenes de Trabajo',
    categoria: 'Operaciones Taller',
    descripcion: 'Planificación, ejecución y seguimiento de servicios.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'pro',
  },
  {
    id: 'vehiculos',
    label: 'Vehículos',
    categoria: 'Operaciones Taller',
    descripcion: 'Fichas, historial y especificaciones por vehículo.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'basico',
  },
  {
    id: 'mis_tareas',
    label: 'Mis Tareas',
    categoria: 'Operaciones Taller',
    descripcion: 'Dashboard operativo para técnicos y asignaciones.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'basico',
  },
  {
    id: 'agenda',
    label: 'Agenda',
    categoria: 'Operaciones Taller',
    descripcion: 'Calendario de citas y programación inteligente.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'basico',
  },
  {
    id: 'catalogo',
    label: 'Catálogo Técnico',
    categoria: 'Operaciones Taller',
    descripcion: 'Manual y fichas técnicas centralizadas.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'pro',
  },
  {
    id: 'productos',
    label: 'Productos',
    categoria: 'Inventario y Compras',
    descripcion: 'Catálogo general con variantes y atributos.',
    obligatorio: true,
    preseleccionado: true,
    minPlan: 'basico',
  },
  {
    id: 'inventario',
    label: 'Inventario',
    categoria: 'Inventario y Compras',
    descripcion: 'Control de stock, bodegas y movimientos.',
    obligatorio: true,
    preseleccionado: true,
    minPlan: 'basico',
  },
  {
    id: 'compras',
    label: 'Compras',
    categoria: 'Inventario y Compras',
    descripcion: 'Órdenes de compra, recepción y costos.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'basico',
  },
  {
    id: 'proveedores',
    label: 'Proveedores',
    categoria: 'Inventario y Compras',
    descripcion: 'Gestión de proveedores y condiciones comerciales.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'basico',
  },
  {
    id: 'finanzas',
    label: 'Finanzas',
    categoria: 'Finanzas y Reportes',
    descripcion: 'Flujo de caja, egresos y conciliaciones.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'pro',
  },
  {
    id: 'analisis_financiero',
    label: 'Análisis Financiero',
    categoria: 'Finanzas y Reportes',
    descripcion: 'Indicadores clave y panel gerencial.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'pro',
    badge: 'Nuevo',
  },
  {
    id: 'contabilidad',
    label: 'Contabilidad',
    categoria: 'Finanzas y Reportes',
    descripcion: 'Integración contable y asientos automáticos.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'enterprise',
  },
  {
    id: 'cuentas_por_cobrar_pagar',
    label: 'Cuentas por Cobrar/Pagar',
    categoria: 'Finanzas y Reportes',
    descripcion: 'Gestión de cartera y proveedores.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'pro',
  },
  {
    id: 'estadisticas',
    label: 'Estadísticas',
    categoria: 'Finanzas y Reportes',
    descripcion: 'Reportes y analítica personalizada.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'pro',
  },
  {
    id: 'nuevo',
    label: 'Nuevo',
    categoria: 'Finanzas y Reportes',
    descripcion: 'Reservado para experiencias beta o lanzamientos.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'pro',
    badge: 'Nuevo',
  },
  {
    id: 'marketing',
    label: 'Marketing',
    categoria: 'Marketing y Comunicación',
    descripcion: 'Campañas y automatizaciones segmentadas.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'pro',
  },
  {
    id: 'publicidad',
    label: 'Publicidad',
    categoria: 'Marketing y Comunicación',
    descripcion: 'Gestión de anuncios y promociones.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'pro',
  },
  {
    id: 'recordatorios',
    label: 'Recordatorios',
    categoria: 'Marketing y Comunicación',
    descripcion: 'Notificaciones programadas multi-canal.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'basico',
  },
  {
    id: 'notificaciones',
    label: 'Notificaciones',
    categoria: 'Marketing y Comunicación',
    descripcion: 'Historial y envío de notificaciones.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'pro',
  },
  {
    id: 'documentos',
    label: 'Documentos SRI',
    categoria: 'Administración y Sistema',
    descripcion: 'Comprobantes electrónicos, emisión y control.',
    obligatorio: true,
    preseleccionado: true,
    minPlan: 'pro',
  },
  {
    id: 'importador',
    label: 'Importar CSV',
    categoria: 'Administración y Sistema',
    descripcion: 'Carga masiva de catálogos y clientes.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'basico',
  },
  {
    id: 'configuracion',
    label: 'Configuración',
    categoria: 'Administración y Sistema',
    descripcion: 'Ajustes generales del negocio.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'basico',
  },
  {
    id: 'backup',
    label: 'Backup & Datos',
    categoria: 'Administración y Sistema',
    descripcion: 'Respaldos y restauración controlada.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'pro',
    adminOnly: true,
  },
  {
    id: 'logs',
    label: 'Logs del Sistema',
    categoria: 'Administración y Sistema',
    descripcion: 'Auditoría y monitoreo técnico.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'enterprise',
    adminOnly: true,
  },
  {
    id: 'historial_notificaciones',
    label: 'Historial de Notificaciones',
    categoria: 'Administración y Sistema',
    descripcion: 'Trazabilidad completa de mensajes enviados.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'pro',
  },
  {
    id: 'gestor_central',
    label: 'Gestor Central',
    categoria: 'Administración y Sistema',
    descripcion: 'Panel maestro para super administradores.',
    obligatorio: false,
    preseleccionado: false,
    minPlan: 'enterprise',
    adminOnly: true,
  },
  {
    id: 'sistema',
    label: 'Sistema',
    categoria: 'Administración y Sistema',
    descripcion: 'Acceso a herramientas y diagnósticos del sistema.',
    obligatorio: false,
    preseleccionado: true,
    minPlan: 'pro',
  },
]);

const OBLIGATORY_MODULES = Object.freeze(
  MODULE_CATALOG.filter((mod) => mod.obligatorio).map((mod) => mod.id)
);

const DEFAULT_BUSINESS_MODULES = Object.freeze(
  MODULE_CATALOG.filter((mod) => mod.obligatorio || mod.preseleccionado).map((mod) => mod.id)
);

module.exports = {
  MODULE_CATALOG,
  OBLIGATORY_MODULES,
  DEFAULT_BUSINESS_MODULES,
};
